add auth
is-miq-2024/backend pull request #11
Opened 2024-11-10 15:27 UTC by andrdegid848

2024-11-11 10:38 UTC, semyonan commented on src/main/kotlin/controllers/AuthController.kt
> +
Не увидела аннотаций в других контроллерах для проверки того, зарегистрировался пользователь или нет, часть операций должны быть доступна без регистрации, часть только с

2024-11-11 10:38 UTC, semyonan commented on src/main/kotlin/entities/User.kt
> +    val username: String,
Почему username

2024-11-11 10:38 UTC, semyonan commented on src/main/kotlin/entities/User.kt
> +    val username: String,
Что с логином было не так?

2024-11-11 21:24 UTC, semyonan commented on src/main/kotlin/controllers/AuthController.kt
> +import org.springframework.web.bind.annotation.*
развернуть *

2024-11-11 21:24 UTC, semyonan commented on src/main/kotlin/configurations/SecurityConfig.kt
> +            .formLogin { form -> form.defaultSuccessUrl("/route", true) }
Если это адрес переадресаций то скорее /search

2024-11-11 21:24 UTC, semyonan commented on src/main/kotlin/services/AuthService.kt
> +            .orElseThrow { UsernameNotFoundException("User not found") }
Добавить username в сообщение, отловить его в advice controller

2024-11-11 21:24 UTC, semyonan commented on src/main/kotlin/services/AuthService.kt
> +            throw RuntimeException("User already exists")
Лучше кастомное исключение, добавить с сообщение username, отловить в advice controllere

2024-11-11 23:49 UTC, andrdegid848 commented on src/main/kotlin/controllers/AuthController.kt
> +
какой проверки в других контроллерах?
мы в security config это обрабатываем, в том числе прописываем доступ по endpoints на данный момент permit All только для regsiter и login

2024-11-12 09:04 UTC, semyonan commented on src/main/kotlin/controllers/AuthController.kt
> +
А все пон, добавь к ним тогда те, которые также доступны без регистрации, это например route/search и мб еще какие-то, все в требованиях есть

2024-11-12 09:06 UTC, semyonan commented on src/main/kotlin/entities/User.kt
> +    val username: String,
Ты не поменял ?

2024-11-12 16:56 UTC, ulyagff requested changes

2024-11-12 16:56 UTC, ulyagff commented on src/main/kotlin/configurations/SecurityConfig.kt
> +                    .requestMatchers("/auth/register", "/auth/login", "/route/search")
GET /route/{id} тоже достуен всем

2024-11-12 16:56 UTC, ulyagff commented on src/main/kotlin/controllers/AuthController.kt
> +    }
и почему нет выхода из аккаунта

2024-11-12 19:26 UTC, ulyagff approved these changes

2024-11-12 19:28 UTC, merged