add entities and dao
is-miq-2024/backend pull request #5
Opened 2024-10-30 17:16 UTC by ulyagff

репозиторий для маршрута и юзера
на юзера тесты не писала, и вообще эта часть должна быть сделана когда будет делаться авторизация и лк

а вот так я запускала это локально: docker run -d -p 27017:27017 --name mongo-on-docker -e MONGO_INITDB_ROOT_USERNAME=mongoadmin -e MONGO_INITDB_ROOT_PASSWORD=secret -e MONGO_INITDB_DATABASE=testdb mongo

2024-10-30 17:19 UTC, semyonan commented on src/main/kotlin/entities/Comment.kt
> +    val timestamp: Long
А в kotlin нету Timestamp класса?

2024-10-30 17:26 UTC, ulyagff commented on src/main/kotlin/entities/Comment.kt
> +    val timestamp: Long
не заметила, заменила на instant

2024-10-31 15:03 UTC, zdarovayrodi commented on src/main/resources/config/application.properties
Унесем в .env?

2024-11-02 17:58 UTC, zdarovayrodi requested changes
@andrdegid848 сделай .env пж

2024-11-04 12:16 UTC, zdarovayrodi commented on src/main/kotlin/configurations/MongoConfig.kt
> +        return MongoClients.create("mongodb://mongoadmin:secret@localhost:27017")
А зачем тогда креды в application.properties?

2024-11-04 13:12 UTC, merged